spring:
  datasource:
    url: jdbc:mysql://localhost:3306/allimi
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        #       show_sql: true
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.orm.jdbc.bind: trace

  thymeleaf:
    prefix: classpath:/templates/   # 기본 템플릿 경로
    suffix: .html                   # 템플릿 파일 확장자
    mode: HTML                      # 처리 모드
    cache: false                    # 개발 중에는 캐싱 비활성화
    encoding: UTF-8                 # 인코딩 설정

naver:
  client:
    id: WlcRMCsyTaeaWCl8CNsq
    secret: EsJP3vBRFM

